[project]
name = "ensures"
version = "0.1.0"
description = "Design by Contract with Functional Programming"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["uv_build >= 0.7.19, <0.9.0"]
build-backend = "uv_build"
